import type { DnsRecord, ZoneDoc } from './types.js';

/**
 * Escape a TXT payload and split it into <=255-byte quoted strings per
 * RFC1035. Escaping happens here as well as at validation time on purpose:
 * the renderer must be safe even if it is ever handed unvalidated input.
 */
export function renderTxt(text: string): string {
  const escaped = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  if (escaped.length <= 255) return `"${escaped}"`;

  const chunks: string[] = [];
  let i = 0;
  while (i < escaped.length) {
    let end = Math.min(i + 255, escaped.length);
    // Never split in the middle of a backslash escape.
    let backslashes = 0;
    for (let j = end - 1; j >= i && escaped[j] === '\\'; j--) backslashes++;
    if (backslashes % 2 === 1) end -= 1;
    chunks.push(`"${escaped.slice(i, end)}"`);
    i = end;
  }
  return chunks.join(' ');
}

/** The RDATA field for one record, already escaped and quoted as needed. */
export function renderRdata(record: DnsRecord): string {
  const d = record.data;
  switch (record.type) {
    case 'A':
    case 'AAAA':
      return (d as { ip: string }).ip;
    case 'CNAME':
    case 'NS':
    case 'PTR':
      return (d as { target: string }).target;
    case 'TXT':
      return renderTxt((d as { text: string }).text);
    case 'MX': {
      const mx = d as { preference: number; exchange: string };
      return `${mx.preference} ${mx.exchange}`;
    }
    case 'SRV': {
      const srv = d as { priority: number; weight: number; port: number; target: string };
      return `${srv.priority} ${srv.weight} ${srv.port} ${srv.target}`;
    }
  }
}

/**
 * Final guard applied to every emitted line. Validation should already make
 * this unreachable; if it ever fires, something upstream let a control
 * character through and we would rather truncate than write a broken zone.
 */
function safeLine(line: string): string {
  return line.replace(/[^ -~]/g, ' ').replace(/\s+$/, '');
}

function pad(value: string, width: number): string {
  return value.length >= width ? `${value} ` : value.padEnd(width, ' ');
}

/** Group ordering: SOA and apex NS first, then by name, then by type. */
function sortRecords(records: DnsRecord[]): DnsRecord[] {
  const typeRank = (t: string) => (t === 'NS' ? 0 : 1);
  return [...records].sort((a, b) => {
    if (a.name === '@' && b.name !== '@') return -1;
    if (b.name === '@' && a.name !== '@') return 1;
    if (a.name !== b.name) return a.name.localeCompare(b.name);
    const rank = typeRank(a.type) - typeRank(b.type);
    if (rank !== 0) return rank;
    if (a.type !== b.type) return a.type.localeCompare(b.type);
    return renderRdata(a).localeCompare(renderRdata(b));
  });
}

/**
 * Render the canonical zone document as an RFC1035 master file.
 *
 * The output is deterministic for a given document: records are sorted, so two
 * sites that have pulled the same serial produce byte-identical files and any
 * drift is visible with a plain diff.
 */
export function renderZone(doc: ZoneDoc): string {
  const out: string[] = [];
  const origin = doc.origin;

  out.push(`; ${origin} - generated by priv-dns, do not edit by hand`);
  out.push(`; serial ${doc.serial} | updated ${doc.updatedAt} by ${safeLine(doc.updatedBy)}`);
  out.push('');
  out.push(`$ORIGIN ${origin}`);
  out.push(`$TTL ${doc.defaultTtl}`);
  out.push('');

  const { soa } = doc;
  out.push(`@       IN  SOA ${soa.mname} ${soa.rname} (`);
  out.push(`            ${String(doc.serial).padEnd(12)}; serial`);
  out.push(`            ${String(soa.refresh).padEnd(12)}; refresh`);
  out.push(`            ${String(soa.retry).padEnd(12)}; retry`);
  out.push(`            ${String(soa.expire).padEnd(12)}; expire`);
  out.push(`            ${String(soa.minimum).padEnd(12)}; minimum`);
  out.push('            )');
  out.push('');

  let lastName: string | null = null;
  for (const record of sortRecords(doc.records)) {
    if (lastName !== null && record.name !== lastName) out.push('');
    lastName = record.name;

    const line =
      `${pad(record.name, 24)}${pad(String(record.ttl), 8)}IN  ` +
      `${pad(record.type, 6)}${renderRdata(record)}`;
    out.push(safeLine(record.comment ? `${line} ; ${record.comment}` : line));
  }

  out.push('');
  return out.join('\n');
}

/* ------------------------------------------------- Unbound local-data ---- */

/** Resolve a possibly-relative name to an absolute one under the origin. */
function absolute(name: string, origin: string): string {
  if (name === '@') return origin;
  if (name.endsWith('.')) return name;
  return `${name}.${origin}`;
}

/**
 * Render the zone as Unbound `local-data` statements.
 *
 * This is deliberately *additive* rather than authoritative. The accompanying
 * `local-zone ... transparent` means Unbound answers from this data when it
 * has a matching name and otherwise falls through to normal recursion - so a
 * public name in the same zone (the control plane's own hostname, for
 * instance) keeps resolving without having to be mirrored here.
 *
 * That is the opposite of a BIND zone file loaded by an authoritative server,
 * which answers NXDOMAIN for anything it does not contain.
 */
export function renderUnbound(doc: ZoneDoc): string {
  const origin = doc.origin;
  const out: string[] = [];

  out.push(`# ${origin} - generated by priv-dns, do not edit by hand`);
  out.push(`# serial ${doc.serial} | updated ${doc.updatedAt}`);
  out.push('server:');
  out.push(`  local-zone: "${origin}" transparent`);
  out.push('');

  for (const record of sortRecords(doc.records)) {
    const name = absolute(record.name, origin);

    // The apex NS is boilerplate for the BIND rendering and would only shadow
    // real delegation data here.
    if (record.type === 'NS' && record.name === '@') continue;

    const rdata = renderRdataAbsolute(record, origin);
    const comment = record.comment ? `  # ${record.comment}` : '';

    // The whole statement is one quoted string in Unbound's config, and TXT
    // rdata is itself quoted - so pick a delimiter the payload does not use.
    // Unbound's parser has no escape sequence that would let us do better.
    const value = `${name} ${record.ttl} IN ${record.type} ${rdata}`;
    const quote = !value.includes('"') ? '"' : (!value.includes("'") ? "'" : null);
    if (quote === null) {
      // Emitting this would be a syntax error, and a bad include stops Unbound
      // from starting at all - which would take DNS down network-wide. Skip
      // the one record and say so, rather than risk the whole file.
      out.push(`  # SKIPPED ${name} ${record.type}: value contains both quote characters`);
      continue;
    }
    out.push(safeLine(`  local-data: ${quote}${value}${quote}${comment}`));

    // A reverse mapping so `dig -x` works for hosts, matching what the
    // OPNsense host-override UI produces.
    if (record.type === 'A' || record.type === 'AAAA') {
      const ip = (record.data as { ip: string }).ip;
      if (!record.name.startsWith('*')) {
        out.push(safeLine(`  local-data-ptr: "${ip} ${name}"`));
      }
    }
  }

  out.push('');
  return out.join('\n');
}

/** Like renderRdata, but target names are made absolute for local-data. */
function renderRdataAbsolute(record: DnsRecord, origin: string): string {
  const d = record.data;
  switch (record.type) {
    case 'CNAME':
    case 'NS':
    case 'PTR':
      return absolute((d as { target: string }).target, origin);
    case 'MX': {
      const mx = d as { preference: number; exchange: string };
      return `${mx.preference} ${absolute(mx.exchange, origin)}`;
    }
    case 'SRV': {
      const s = d as { priority: number; weight: number; port: number; target: string };
      return `${s.priority} ${s.weight} ${s.port} ${absolute(s.target, origin)}`;
    }
    default:
      return renderRdata(record);
  }
}

/* ------------------------------------------------------- hosts file ------ */

/**
 * Render the zone as a hosts file (`IP name`), for consumers that read one:
 * dnsmasq `addn-hosts`, Pi-hole, AdGuard Home, or plain /etc/hosts.
 *
 * A hosts file can only express address records, so CNAMEs are *flattened* -
 * followed within the zone to the address they ultimately point at. Records
 * that have no hosts-file equivalent at all (MX, SRV, TXT, NS) are listed in a
 * trailing comment rather than dropped silently, so it is obvious what this
 * format cannot carry.
 */
export function renderHosts(doc: ZoneDoc): string {
  const origin = doc.origin;
  const fqdn = (n: string) => absolute(n, origin).replace(/\.$/, '');

  // name -> address, for flattening CNAME chains.
  const addresses = new Map<string, string[]>();
  for (const r of doc.records) {
    if (r.type !== 'A' && r.type !== 'AAAA') continue;
    const key = fqdn(r.name);
    const list = addresses.get(key) ?? [];
    list.push((r.data as { ip: string }).ip);
    addresses.set(key, list);
  }

  const cnames = new Map<string, string>();
  for (const r of doc.records) {
    if (r.type !== 'CNAME') continue;
    cnames.set(fqdn(r.name), fqdn((r.data as { target: string }).target));
  }

  /** Follow a CNAME chain to its addresses, guarding against loops. */
  const resolve = (name: string): string[] => {
    const seen = new Set<string>();
    let cur = name;
    while (!addresses.has(cur)) {
      const next = cnames.get(cur);
      if (!next || seen.has(next)) return [];
      seen.add(next);
      cur = next;
    }
    return addresses.get(cur) ?? [];
  };

  const out: string[] = [];
  out.push(`# ${origin} - generated by priv-dns, do not edit by hand`);
  out.push(`# serial ${doc.serial} | updated ${doc.updatedAt}`);
  out.push('');

  const lines: string[] = [];
  const unsupported: string[] = [];

  for (const record of sortRecords(doc.records)) {
    const name = fqdn(record.name);
    if (record.type === 'A' || record.type === 'AAAA') {
      const ip = (record.data as { ip: string }).ip;
      const note = record.comment ? `  # ${record.comment}` : '';
      lines.push(safeLine(`${ip.padEnd(16)} ${name}${note}`));
    } else if (record.type === 'CNAME') {
      const ips = resolve(name);
      if (ips.length === 0) {
        unsupported.push(`${name} CNAME -> target has no address in this zone`);
        continue;
      }
      const target = fqdn((record.data as { target: string }).target);
      for (const ip of ips) {
        lines.push(safeLine(`${ip.padEnd(16)} ${name}  # flattened from ${target}`));
      }
    } else if (record.name !== '@' || record.type !== 'NS') {
      unsupported.push(`${name} ${record.type}`);
    }
  }

  // A wildcard cannot be expressed in a hosts file at all.
  const emitted = lines.filter((l) => !l.includes('*'));
  const wildcards = lines.filter((l) => l.includes('*'));
  out.push(...emitted);

  if (wildcards.length || unsupported.length) {
    out.push('');
    out.push('# Not representable in a hosts file:');
    for (const w of wildcards) out.push(`#   ${w.trim()}  (wildcard)`);
    for (const u of unsupported) out.push(`#   ${u}`);
  }

  out.push('');
  return out.join('\n');
}
